import "dotenv/config";
import { getPoolForScripts, db } from "./index";
import { categories, products, reviews } from "./schema";
const pool = getPoolForScripts();

type SeedProduct = {
  slug: string;
  name: string;
  categorySlug: string;
  price: number;
  compareAtPrice?: number;
  rating: number; // x10
  reviewCount: number;
  shortDescription: string;
  description: string;
  features: string[];
  gallery: string[];
  emoji: string;
  gradientFrom: string;
  gradientTo: string;
  badge?: string;
  ageRange: string;
  brand: string;
  stock: number;
  featured?: boolean;
  bestseller?: boolean;
};

const categoryData = [
  {
    slug: "building-blocks",
    name: "Building Blocks",
    tagline: "Snap, stack & build big dreams",
    emoji: "🧱",
    gradientFrom: "#FF7A59",
    gradientTo: "#FFB259",
    sortOrder: 1,
  },
  {
    slug: "plush-toys",
    name: "Plush & Soft Toys",
    tagline: "Huggable friends for cosy days",
    emoji: "🧸",
    gradientFrom: "#FB7185",
    gradientTo: "#FDA4AF",
    sortOrder: 2,
  },
  {
    slug: "remote-control",
    name: "Remote Control",
    tagline: "Zoom, race & remote-control fun",
    emoji: "🚗",
    gradientFrom: "#38BDF8",
    gradientTo: "#7DD3FC",
    sortOrder: 3,
  },
  {
    slug: "dolls",
    name: "Dolls & Playsets",
    tagline: "Dolls, playsets & make-believe",
    emoji: "👑",
    gradientFrom: "#A78BFA",
    gradientTo: "#C4B5FD",
    sortOrder: 4,
  },
  {
    slug: "educational",
    name: "Learning & STEM",
    tagline: "Learn, experiment & grow",
    emoji: "🔬",
    gradientFrom: "#34D399",
    gradientTo: "#6EE7B7",
    sortOrder: 5,
  },
  {
    slug: "arts-crafts",
    name: "Arts & Crafts",
    tagline: "Create, colour & get crafty",
    emoji: "🎨",
    gradientFrom: "#F472B6",
    gradientTo: "#F9A8D4",
    sortOrder: 6,
  },
  {
    slug: "outdoor",
    name: "Outdoor & Sports",
    tagline: "Sun, sports & active play",
    emoji: "🪁",
    gradientFrom: "#22D3EE",
    gradientTo: "#67E8F9",
    sortOrder: 7,
  },
  {
    slug: "party",
    name: "Party & Celebration",
    tagline: "Everything for the perfect party",
    emoji: "🎉",
    gradientFrom: "#FBBF24",
    gradientTo: "#FCD34D",
    sortOrder: 8,
  },
];

const productData: SeedProduct[] = [
  // Building Blocks
  {
    slug: "mega-castle-builder-620",
    name: "Mega Castle Builder — 620 Pieces",
    categorySlug: "building-blocks",
    price: 6499,
    compareAtPrice: 8999,
    rating: 48,
    reviewCount: 214,
    shortDescription: "A 620-piece medieval castle set with knights, dragons and a working drawbridge.",
    description:
      "Build a mighty fortress brick by brick! The Mega Castle Builder comes with 620 vibrant, precision-moulded blocks, four mini-figures, a fire-breathing dragon and a drawbridge that really lifts. Compatible with all major building-block brands, it keeps little architects engaged for hours while sharpening spatial reasoning and patience.",
    features: [
      "620 durable ABS blocks in 12 colours",
      "4 knight & princess mini-figures included",
      "Working drawbridge and secret trapdoor",
      "Step-by-step full-colour instruction booklet",
      "Compatible with leading brick brands",
    ],
    gallery: ["🏰", "🧱", "🐉", "⚔️"],
    emoji: "🏰",
    gradientFrom: "#FF7A59",
    gradientTo: "#FFB259",
    badge: "Bestseller",
    ageRange: "6-12 yrs",
    brand: "BrickWorks",
    stock: 42,
    featured: true,
    bestseller: true,
  },
  {
    slug: "rainbow-starter-bricks-150",
    name: "Rainbow Starter Bricks — 150 Pieces",
    categorySlug: "building-blocks",
    price: 2499,
    rating: 46,
    reviewCount: 138,
    shortDescription: "Chunky, easy-grip bricks perfect for first-time little builders.",
    description:
      "Big, bright and easy to grip, these 150 chunky bricks are designed for tiny hands. Rounded edges and vivid colours make them the perfect first construction set, encouraging creativity, colour recognition and fine-motor skills. Stored in a handy reusable tub for quick tidy-ups.",
    features: [
      "150 oversized easy-grip bricks",
      "Rounded, child-safe edges",
      "Reusable storage tub with handle",
      "Boosts colour recognition & motor skills",
    ],
    gallery: ["🌈", "🧱", "🟦", "🟨"],
    emoji: "🌈",
    gradientFrom: "#FF9F45",
    gradientTo: "#FFC470",
    ageRange: "2-5 yrs",
    brand: "BrickWorks",
    stock: 88,
  },
  {
    slug: "space-station-explorer-480",
    name: "Space Station Explorer — 480 Pieces",
    categorySlug: "building-blocks",
    price: 5999,
    compareAtPrice: 7499,
    rating: 49,
    reviewCount: 96,
    shortDescription: "Assemble a glow-in-the-dark orbital station with rover and astronauts.",
    description:
      "Blast off to adventure! This 480-piece set builds a detailed orbital space station complete with a detachable shuttle, moon rover and two astronaut figures. Glow-in-the-dark elements light up the galaxy at bedtime, sparking a lifelong love of science and space.",
    features: [
      "480 pieces with glow-in-the-dark parts",
      "Detachable shuttle & moon rover",
      "2 astronaut mini-figures",
      "Poster of the finished build included",
    ],
    gallery: ["🚀", "🛰️", "👨‍🚀", "🌌"],
    emoji: "🚀",
    gradientFrom: "#F97316",
    gradientTo: "#FDBA74",
    badge: "New",
    ageRange: "7-14 yrs",
    brand: "BrickWorks",
    stock: 30,
    featured: true,
  },
  {
    slug: "magnetic-tiles-glow-64",
    name: "Magnetic Glow Tiles — 64 Pieces",
    categorySlug: "building-blocks",
    price: 4299,
    rating: 47,
    reviewCount: 172,
    shortDescription: "Translucent magnetic tiles that snap into endless 3D creations.",
    description:
      "Watch imagination click into place with 64 translucent magnetic tiles. Strong magnets snap smoothly on every edge so kids can build towers, castles and rockets that catch the light beautifully. A modern STEM favourite for open-ended play.",
    features: [
      "64 strong translucent magnetic tiles",
      "Snap on every edge for easy building",
      "Idea booklet with 20+ builds",
      "Develops geometry & engineering skills",
    ],
    gallery: ["🔷", "🔶", "💠", "🟪"],
    emoji: "🔷",
    gradientFrom: "#FB923C",
    gradientTo: "#FCD34D",
    ageRange: "3-10 yrs",
    brand: "MagnaPlay",
    stock: 55,
    bestseller: true,
  },
  // Plush
  {
    slug: "cuddle-cloud-teddy-bear",
    name: "Cuddle Cloud Teddy Bear",
    categorySlug: "plush-toys",
    price: 2299,
    compareAtPrice: 2999,
    rating: 49,
    reviewCount: 305,
    shortDescription: "Ultra-soft 40cm teddy stuffed with hypoallergenic cloud fibre.",
    description:
      "Meet the softest bear in town. Standing 40cm tall and filled with premium hypoallergenic cloud fibre, this teddy is machine-washable and impossibly huggable. A timeless first friend for birthdays, new arrivals and comfort at bedtime.",
    features: [
      "40cm tall, premium plush fabric",
      "Hypoallergenic cloud-fibre filling",
      "Machine washable, colour-safe",
      "Embroidered eyes — no small parts",
    ],
    gallery: ["🧸", "💗", "🎀", "☁️"],
    emoji: "🧸",
    gradientFrom: "#FB7185",
    gradientTo: "#FDA4AF",
    badge: "Bestseller",
    ageRange: "0+ yrs",
    brand: "SnuggleCo",
    stock: 120,
    featured: true,
    bestseller: true,
  },
  {
    slug: "rainbow-unicorn-plush",
    name: "Stardust the Rainbow Unicorn",
    categorySlug: "plush-toys",
    price: 2799,
    rating: 48,
    reviewCount: 189,
    shortDescription: "A magical 35cm unicorn with a shimmering rainbow mane.",
    description:
      "Every dream needs a little magic. Stardust is a 35cm plush unicorn with a glittering horn and a silky rainbow mane kids love to brush. Soft, sturdy and endlessly cuddly — a guaranteed party hit.",
    features: [
      "35cm plush with shimmer horn",
      "Silky brushable rainbow mane",
      "Super-soft minky fabric",
      "Spot-clean friendly",
    ],
    gallery: ["🦄", "🌈", "✨", "💜"],
    emoji: "🦄",
    gradientFrom: "#F472B6",
    gradientTo: "#C4B5FD",
    ageRange: "2+ yrs",
    brand: "SnuggleCo",
    stock: 74,
    featured: true,
  },
  {
    slug: "sleepy-sloth-plush",
    name: "Sleepy Sloth Cuddle Buddy",
    categorySlug: "plush-toys",
    price: 1899,
    rating: 47,
    reviewCount: 121,
    shortDescription: "A weighted, huggable sloth that helps little ones settle down.",
    description:
      "The Sleepy Sloth's gently weighted body offers calming comfort at nap time. Long velcro-tipped arms let it hug cots, prams or a favourite arm. Beautifully soft and endlessly loveable.",
    features: [
      "Gently weighted for calming comfort",
      "Velcro arms to hang anywhere",
      "Velvety soft plush fabric",
      "30cm from paw to paw",
    ],
    gallery: ["🦥", "💤", "🌙", "🍃"],
    emoji: "🦥",
    gradientFrom: "#F9A8D4",
    gradientTo: "#FBCFE8",
    ageRange: "1+ yrs",
    brand: "SnuggleCo",
    stock: 63,
  },
  {
    slug: "jumbo-dino-plush",
    name: "Jumbo Rex Dinosaur Plush",
    categorySlug: "plush-toys",
    price: 3499,
    compareAtPrice: 4299,
    rating: 48,
    reviewCount: 87,
    shortDescription: "A giant 60cm friendly T-Rex that's soft as a cloud.",
    description:
      "Roar! This 60cm friendly T-Rex is big on cuddles and even bigger on personality. Soft plush spikes and a squishy belly make it the ultimate adventure companion — day or night.",
    features: [
      "Giant 60cm plush dinosaur",
      "Soft, bendable plush spikes",
      "Reinforced seams for rough play",
      "Surface-washable",
    ],
    gallery: ["🦖", "🌿", "🥚", "💚"],
    emoji: "🦖",
    gradientFrom: "#F97316",
    gradientTo: "#FB7185",
    ageRange: "2+ yrs",
    brand: "SnuggleCo",
    stock: 38,
    bestseller: true,
  },
  // Remote Control
  {
    slug: "thunder-drift-rc-car",
    name: "Thunder Drift RC Racing Car",
    categorySlug: "remote-control",
    price: 8999,
    compareAtPrice: 11999,
    rating: 47,
    reviewCount: 143,
    shortDescription: "2.4GHz high-speed drift car reaching 20km/h with LED underglow.",
    description:
      "Feel the need for speed! The Thunder Drift rips across floors at up to 20km/h with responsive 2.4GHz control, four-wheel drift tyres and glowing LED underglow. A rechargeable battery and USB cable are included so the racing never stops.",
    features: [
      "2.4GHz control, up to 30m range",
      "Reaches 20km/h with drift tyres",
      "Colour-shift LED underglow",
      "Rechargeable battery + USB cable",
      "Anti-collision shock frame",
    ],
    gallery: ["🏎️", "💨", "🔋", "🏁"],
    emoji: "🏎️",
    gradientFrom: "#38BDF8",
    gradientTo: "#818CF8",
    badge: "Bestseller",
    ageRange: "6+ yrs",
    brand: "VeloxRC",
    stock: 47,
    featured: true,
    bestseller: true,
  },
  {
    slug: "mighty-monster-truck-rc",
    name: "Mighty Monster Truck RC",
    categorySlug: "remote-control",
    price: 10499,
    rating: 48,
    reviewCount: 92,
    shortDescription: "All-terrain 4x4 monster truck that climbs, jumps and never quits.",
    description:
      "Conquer any terrain! This rugged 4x4 monster truck powers over sand, grass and gravel with oversized grip tyres and full suspension. Perform 360° spins and stunts with intuitive controls the whole family will fight over.",
    features: [
      "4x4 all-terrain drive",
      "Oversized shock-absorbing tyres",
      "360° spins & stunt mode",
      "Rechargeable 1200mAh battery",
    ],
    gallery: ["🚙", "🏔️", "🪨", "⚡"],
    emoji: "🚙",
    gradientFrom: "#0EA5E9",
    gradientTo: "#38BDF8",
    ageRange: "6+ yrs",
    brand: "VeloxRC",
    stock: 34,
    featured: true,
  },
  {
    slug: "sky-scout-mini-drone",
    name: "Sky Scout Mini Drone",
    categorySlug: "remote-control",
    price: 12999,
    compareAtPrice: 15999,
    rating: 46,
    reviewCount: 68,
    shortDescription: "Beginner-friendly drone with altitude hold and one-key stunts.",
    description:
      "Take flight with the Sky Scout! Altitude-hold keeps it steady while headless mode makes flying simple for first-timers. One-key take-off, landing and 360° flips make every backyard an air show. Includes prop guards for safe indoor fun.",
    features: [
      "Altitude hold & headless mode",
      "One-key take-off, land & flips",
      "Protective prop guards included",
      "2 rechargeable batteries",
    ],
    gallery: ["🚁", "🛸", "🎮", "🌤️"],
    emoji: "🚁",
    gradientFrom: "#22D3EE",
    gradientTo: "#7DD3FC",
    badge: "New",
    ageRange: "8+ yrs",
    brand: "VeloxRC",
    stock: 22,
  },
  // Dolls
  {
    slug: "dreamville-dollhouse",
    name: "Dreamville Deluxe Dollhouse",
    categorySlug: "dolls",
    price: 8999,
    compareAtPrice: 11499,
    rating: 49,
    reviewCount: 156,
    shortDescription: "A three-storey dollhouse with lights, sounds and 25 accessories.",
    description:
      "Welcome to Dreamville! This charming three-storey dollhouse features working lights, doorbell sounds, a movable lift and 25 detailed furniture pieces across six rooms. Open-back design lets multiple children play together for endless storytelling.",
    features: [
      "3 storeys, 6 furnished rooms",
      "Working lights & doorbell sounds",
      "25 furniture & accessory pieces",
      "Open-back for group play",
    ],
    gallery: ["🏠", "🛋️", "🚪", "💡"],
    emoji: "🏠",
    gradientFrom: "#A78BFA",
    gradientTo: "#C4B5FD",
    badge: "Bestseller",
    ageRange: "3-8 yrs",
    brand: "LittleLane",
    stock: 26,
    featured: true,
    bestseller: true,
  },
  {
    slug: "fashion-friends-doll-set",
    name: "Fashion Friends Doll & Wardrobe Set",
    categorySlug: "dolls",
    price: 3999,
    rating: 47,
    reviewCount: 110,
    shortDescription: "Two posable dolls with 20 mix-and-match outfit pieces.",
    description:
      "Style, swap and shine! This set includes two fully posable 28cm dolls with silky brushable hair and 20 mix-and-match fashion pieces, from party dresses to sneakers. Encourages creativity, storytelling and a love of self-expression.",
    features: [
      "2 posable 28cm dolls",
      "20 outfit & accessory pieces",
      "Silky brushable hair",
      "Mix-and-match styling fun",
    ],
    gallery: ["👗", "👝", "👠", "💄"],
    emoji: "👗",
    gradientFrom: "#C084FC",
    gradientTo: "#F0ABFC",
    ageRange: "4-9 yrs",
    brand: "LittleLane",
    stock: 58,
  },
  {
    slug: "baby-care-nursery-playset",
    name: "Baby Care Nursery Playset",
    categorySlug: "dolls",
    price: 4599,
    compareAtPrice: 5499,
    rating: 48,
    reviewCount: 73,
    shortDescription: "A soft baby doll with cot, bottle, and nursery accessories.",
    description:
      "Nurture and care! This tender playset comes with a huggable soft-bodied baby doll, a fold-out cot, feeding bottle, and adorable nursery accessories. Perfect for imaginative role-play that builds empathy and responsibility.",
    features: [
      "Soft-bodied cuddle baby doll",
      "Fold-out cot & bedding",
      "Bottle, bib & care accessories",
      "Encourages nurturing play",
    ],
    gallery: ["👶", "🍼", "🛏️", "🧴"],
    emoji: "👶",
    gradientFrom: "#D8B4FE",
    gradientTo: "#FBCFE8",
    ageRange: "3-7 yrs",
    brand: "LittleLane",
    stock: 41,
    featured: true,
  },
  // Educational
  {
    slug: "young-scientist-lab-kit",
    name: "Young Scientist Mega Lab Kit",
    categorySlug: "educational",
    price: 5499,
    compareAtPrice: 6999,
    rating: 49,
    reviewCount: 201,
    shortDescription: "48 safe experiments — volcanoes, crystals, slime and more.",
    description:
      "Spark a lifelong love of science! This mega lab kit guides kids through 48 safe, exciting experiments — erupting volcanoes, growing crystals, fizzing reactions and stretchy slime. Includes goggles, beakers and a full-colour experiment manual.",
    features: [
      "48 safe, guided experiments",
      "Goggles, beakers & tools included",
      "Full-colour illustrated manual",
      "STEM-approved learning fun",
    ],
    gallery: ["🔬", "🧪", "🌋", "💎"],
    emoji: "🔬",
    gradientFrom: "#34D399",
    gradientTo: "#6EE7B7",
    badge: "Bestseller",
    ageRange: "8-14 yrs",
    brand: "BrightMinds",
    stock: 49,
    featured: true,
    bestseller: true,
  },
  {
    slug: "abc-learning-tablet",
    name: "ABC Interactive Learning Tablet",
    categorySlug: "educational",
    price: 3299,
    rating: 46,
    reviewCount: 164,
    shortDescription: "A talking tablet teaching letters, numbers, words and songs.",
    description:
      "Learning made joyful! This chunky, child-proof tablet teaches the alphabet, numbers, spelling and animal sounds through 6 interactive modes and cheerful songs. Volume control and auto-off keep it parent-approved.",
    features: [
      "6 interactive learning modes",
      "Letters, numbers, words & music",
      "Child-proof, easy-grip design",
      "Volume control & auto-off",
    ],
    gallery: ["📱", "🔤", "🔢", "🎵"],
    emoji: "📱",
    gradientFrom: "#10B981",
    gradientTo: "#5EEAD4",
    ageRange: "2-6 yrs",
    brand: "BrightMinds",
    stock: 82,
  },
  {
    slug: "build-a-robot-stem-kit",
    name: "Build-A-Robot Coding STEM Kit",
    categorySlug: "educational",
    price: 7999,
    compareAtPrice: 9499,
    rating: 48,
    reviewCount: 79,
    shortDescription: "Assemble and code your own motorised, obstacle-dodging robot.",
    description:
      "Meet your first robot! Kids build a real motorised robot then program it to move, turn and dodge obstacles using a simple drag-and-drop app. A brilliant introduction to engineering, logic and coding that grows with your child.",
    features: [
      "Buildable motorised robot",
      "Drag-and-drop coding app",
      "Obstacle-detection sensor",
      "Rechargeable & reprogrammable",
    ],
    gallery: ["🤖", "⚙️", "🔩", "💻"],
    emoji: "🤖",
    gradientFrom: "#059669",
    gradientTo: "#34D399",
    badge: "New",
    ageRange: "8+ yrs",
    brand: "BrightMinds",
    stock: 31,
    featured: true,
  },
  {
    slug: "wooden-shape-puzzle-set",
    name: "Wooden Shapes & Numbers Puzzle Set",
    categorySlug: "educational",
    price: 1899,
    rating: 47,
    reviewCount: 96,
    shortDescription: "Chunky wooden puzzles teaching shapes, colours and counting.",
    description:
      "Crafted from smooth, sustainable wood, this set of three chunky puzzles teaches shapes, colours and counting through playful problem-solving. Easy-grip pegs are perfect for developing little hands.",
    features: [
      "3 chunky wooden puzzles",
      "Shapes, colours & numbers",
      "Sustainable wood, non-toxic paint",
      "Easy-grip pegs for small hands",
    ],
    gallery: ["🧩", "🔺", "🟢", "🔢"],
    emoji: "🧩",
    gradientFrom: "#4ADE80",
    gradientTo: "#86EFAC",
    ageRange: "2-5 yrs",
    brand: "BrightMinds",
    stock: 67,
  },
  // Arts & Crafts
  {
    slug: "super-art-studio-150",
    name: "Super Art Studio — 150 Pieces",
    categorySlug: "arts-crafts",
    price: 3499,
    compareAtPrice: 4499,
    rating: 48,
    reviewCount: 188,
    shortDescription: "A complete art case with crayons, markers, paints and pencils.",
    description:
      "Everything a young artist needs in one beautiful case! 150 premium pieces including crayons, washable markers, coloured pencils, watercolour paints and a brush, all in a sturdy carry case. Non-toxic and endlessly inspiring.",
    features: [
      "150 premium art supplies",
      "Crayons, markers, pencils & paints",
      "Sturdy fold-out carry case",
      "Non-toxic & washable",
    ],
    gallery: ["🎨", "🖍️", "🖌️", "✏️"],
    emoji: "🎨",
    gradientFrom: "#F472B6",
    gradientTo: "#F9A8D4",
    badge: "Bestseller",
    ageRange: "4+ yrs",
    brand: "DoodleDen",
    stock: 71,
    featured: true,
    bestseller: true,
  },
  {
    slug: "sparkle-jewellery-maker",
    name: "Sparkle Jewellery Maker Kit",
    categorySlug: "arts-crafts",
    price: 2299,
    rating: 47,
    reviewCount: 102,
    shortDescription: "Design bracelets and necklaces with 600+ beads and charms.",
    description:
      "Create dazzling accessories! With over 600 colourful beads, charms and stretch cords, this kit lets kids design bracelets, necklaces and keyrings. A wonderful way to build focus, patterns and personal style.",
    features: [
      "600+ beads, charms & cords",
      "Design bracelets & necklaces",
      "Reusable storage tray",
      "Idea guide included",
    ],
    gallery: ["💍", "📿", "💎", "🌟"],
    emoji: "💍",
    gradientFrom: "#EC4899",
    gradientTo: "#F9A8D4",
    ageRange: "5+ yrs",
    brand: "DoodleDen",
    stock: 59,
  },
  {
    slug: "squishy-clay-fun-pack",
    name: "Squishy Air-Dry Clay Fun Pack",
    categorySlug: "arts-crafts",
    price: 1499,
    rating: 46,
    reviewCount: 84,
    shortDescription: "24 vivid clay colours with moulds and modelling tools.",
    description:
      "Squish, sculpt and create! This pack includes 24 vibrant blocks of soft air-dry clay, moulding tools and fun shape stamps. Light and non-sticky, it air-dries to keep every masterpiece forever.",
    features: [
      "24 vivid air-dry clay colours",
      "Moulds, stamps & tools included",
      "Soft, non-sticky & non-toxic",
      "Air-dries — no baking needed",
    ],
    gallery: ["🎭", "🌈", "🖐️", "⭐"],
    emoji: "🎭",
    gradientFrom: "#F9A8D4",
    gradientTo: "#FDBA74",
    ageRange: "3+ yrs",
    brand: "DoodleDen",
    stock: 93,
    bestseller: true,
  },
  // Outdoor
  {
    slug: "soaring-eagle-kite",
    name: "Soaring Eagle Delta Kite",
    categorySlug: "outdoor",
    price: 1499,
    rating: 47,
    reviewCount: 76,
    shortDescription: "An easy-launch delta kite with a 1.8m wingspan and long tails.",
    description:
      "Catch the breeze! This eye-catching eagle kite launches easily and soars high with a 1.8m wingspan and colourful streaming tails. Comes with a sturdy handle and 60m of line — perfect for beach days and park outings.",
    features: [
      "1.8m wingspan, easy launch",
      "60m line with grip handle",
      "Durable ripstop fabric",
      "Ready to fly in minutes",
    ],
    gallery: ["🪁", "🦅", "🌬️", "☀️"],
    emoji: "🪁",
    gradientFrom: "#22D3EE",
    gradientTo: "#67E8F9",
    ageRange: "5+ yrs",
    brand: "PlayAir",
    stock: 64,
    featured: true,
  },
  {
    slug: "pro-football-size-4",
    name: "Pro Match Football — Size 4",
    categorySlug: "outdoor",
    price: 1999,
    compareAtPrice: 2599,
    rating: 48,
    reviewCount: 132,
    shortDescription: "A durable size-4 match ball with true-flight machine-stitched panels.",
    description:
      "Play like a pro! This size-4 football features machine-stitched panels for true flight, a soft-touch PU cover and a butyl bladder for lasting air retention. Built for streets, parks and academy training alike.",
    features: [
      "Machine-stitched for true flight",
      "Soft-touch durable PU cover",
      "Air-retaining butyl bladder",
      "Size 4 — ideal for ages 8-12",
    ],
    gallery: ["⚽", "🥅", "🏆", "👟"],
    emoji: "⚽",
    gradientFrom: "#06B6D4",
    gradientTo: "#22D3EE",
    ageRange: "6+ yrs",
    brand: "PlayAir",
    stock: 110,
    bestseller: true,
  },
  {
    slug: "bubble-blaster-2000",
    name: "Bubble Blaster 2000",
    categorySlug: "outdoor",
    price: 1299,
    rating: 46,
    reviewCount: 148,
    shortDescription: "An automatic blaster that fires thousands of bubbles per minute.",
    description:
      "Bubble mania! Pull the trigger and unleash thousands of shimmering bubbles per minute. Lightweight and easy to refill, the Bubble Blaster 2000 turns any garden or party into an instant celebration. Includes two bottles of solution.",
    features: [
      "Thousands of bubbles per minute",
      "Lightweight easy-grip design",
      "2 bottles of solution included",
      "Instant party fun",
    ],
    gallery: ["🫧", "🔫", "🌈", "🎈"],
    emoji: "🫧",
    gradientFrom: "#38BDF8",
    gradientTo: "#A5F3FC",
    ageRange: "3+ yrs",
    brand: "PlayAir",
    stock: 130,
    featured: true,
  },
  // Party
  {
    slug: "birthday-party-mega-pack",
    name: "Birthday Party Mega Pack (Serves 16)",
    categorySlug: "party",
    price: 2999,
    compareAtPrice: 3999,
    rating: 48,
    reviewCount: 167,
    shortDescription: "Everything for 16 guests — plates, cups, hats, banners and more.",
    description:
      "The ultimate party in a box! This coordinated pack serves 16 guests with themed plates, cups, napkins, party hats, a happy-birthday banner, balloons and tableware. Simply add cake and let the celebration begin.",
    features: [
      "Serves 16 guests",
      "Plates, cups, napkins & hats",
      "Happy-birthday banner & balloons",
      "Coordinated bright theme",
    ],
    gallery: ["🎉", "🎂", "🎈", "🎊"],
    emoji: "🎉",
    gradientFrom: "#FBBF24",
    gradientTo: "#FCD34D",
    badge: "Bestseller",
    ageRange: "All ages",
    brand: "PartyPop",
    stock: 96,
    featured: true,
    bestseller: true,
  },
  {
    slug: "pinata-surprise-donkey",
    name: "Fiesta Surprise Piñata",
    categorySlug: "party",
    price: 1799,
    rating: 47,
    reviewCount: 58,
    shortDescription: "A colourful pull-string piñata ready to fill with treats.",
    description:
      "Add a burst of excitement! This vibrant pull-string piñata is safe for all ages — no bat needed. Fill it with sweets and toys, and let every guest pull a ribbon until the surprises rain down.",
    features: [
      "Safe no-swing pull-string design",
      "Holds up to 1kg of treats",
      "Bright, sturdy tissue build",
      "Ribbons for up to 12 kids",
    ],
    gallery: ["🪅", "🍬", "🎀", "🎊"],
    emoji: "🪅",
    gradientFrom: "#F59E0B",
    gradientTo: "#FBBF24",
    ageRange: "All ages",
    brand: "PartyPop",
    stock: 47,
  },
  {
    slug: "party-favour-treasure-box",
    name: "Party Favour Treasure Box (48 pcs)",
    categorySlug: "party",
    price: 1599,
    compareAtPrice: 2199,
    rating: 46,
    reviewCount: 64,
    shortDescription: "48 assorted mini toys and trinkets for goody bags.",
    description:
      "Send every guest home smiling! This treasure box packs 48 assorted mini toys — spinning tops, mini puzzles, stickers, whistles and more — perfectly sized for goody bags and lucky-dip games.",
    features: [
      "48 assorted mini toys",
      "Ideal for goody bags & prizes",
      "Great value party filler",
      "Bright, kid-approved variety",
    ],
    gallery: ["🎁", "🪀", "🨂", "🏅"],
    emoji: "🎁",
    gradientFrom: "#FCD34D",
    gradientTo: "#FDE68A",
    ageRange: "3+ yrs",
    brand: "PartyPop",
    stock: 78,
    bestseller: true,
  },
];

const reviewTemplates = [
  {
    author: "Ayesha Khan",
    location: "Karachi",
    rating: 5,
    title: "My son is obsessed!",
    body: "Fantastic quality and arrived beautifully packed. My son hasn't put it down since it arrived. Worth every rupee!",
  },
  {
    author: "Bilal Ahmed",
    location: "Lahore",
    rating: 5,
    title: "Excellent value",
    body: "Sturdy, colourful and exactly as pictured. Delivery to Lahore was quicker than expected. Highly recommend.",
  },
  {
    author: "Fatima Malik",
    location: "Islamabad",
    rating: 4,
    title: "Great gift choice",
    body: "Bought this for my niece's birthday and it was the star of the party. Lovely finish, would buy again.",
  },
  {
    author: "Hamza Sheikh",
    location: "Rawalpindi",
    rating: 5,
    title: "Better than expected",
    body: "The quality really surprised me for the price. Feels premium and my kids play with it every single day.",
  },
  {
    author: "Zainab Raza",
    location: "Faisalabad",
    rating: 5,
    title: "Keeps them busy for hours",
    body: "Finally something that holds their attention away from screens. Safe, well made and lots of fun.",
  },
  {
    author: "Usman Tariq",
    location: "Multan",
    rating: 4,
    title: "Happy with the purchase",
    body: "Good product overall. Packaging was secure and cash on delivery made it very easy to order.",
  },
  {
    author: "Sana Iqbal",
    location: "Peshawar",
    rating: 5,
    title: "Party hit!",
    body: "This was a huge hit at my daughter's party. Bright, cheerful and great quality. Thank you Kids Party!",
  },
  {
    author: "Ali Hassan",
    location: "Hyderabad",
    rating: 5,
    title: "Superb quality",
    body: "You can tell this is well made. My children love it and it has survived plenty of rough play already.",
  },
];

async function seed() {
  console.log("🌱 Seeding database...");

  await db.delete(reviews);
  await db.delete(products);
  await db.delete(categories);

  await db.insert(categories).values(categoryData);
  console.log(`✔ Inserted ${categoryData.length} categories`);

  await db.insert(products).values(
    productData.map((p) => ({
      slug: p.slug,
      name: p.name,
      categorySlug: p.categorySlug,
      price: p.price,
      compareAtPrice: p.compareAtPrice ?? null,
      rating: p.rating,
      reviewCount: p.reviewCount,
      shortDescription: p.shortDescription,
      description: p.description,
      features: p.features,
      gallery: p.gallery,
      emoji: p.emoji,
      gradientFrom: p.gradientFrom,
      gradientTo: p.gradientTo,
      badge: p.badge ?? null,
      ageRange: p.ageRange,
      brand: p.brand,
      stock: p.stock,
      featured: p.featured ?? false,
      bestseller: p.bestseller ?? false,
    })),
  );
  console.log(`✔ Inserted ${productData.length} products`);

  const reviewRows: (typeof reviews.$inferInsert)[] = [];
  for (const p of productData) {
    // 3-4 reviews per product, deterministic selection
    const count = 3 + (p.slug.length % 2);
    const start = p.slug.charCodeAt(0) % reviewTemplates.length;
    for (let i = 0; i < count; i++) {
      const t = reviewTemplates[(start + i) % reviewTemplates.length];
      reviewRows.push({
        productSlug: p.slug,
        author: t.author,
        location: t.location,
        rating: t.rating,
        title: t.title,
        body: t.body,
        verified: true,
        createdAt: new Date(Date.now() - (i + 1) * 86400000 * (2 + (i % 4))),
      });
    }
  }
  await db.insert(reviews).values(reviewRows);
  console.log(`✔ Inserted ${reviewRows.length} reviews`);

  console.log("✅ Seed complete");
}

seed()
  .then(async () => {
    await pool.end();
    process.exit(0);
  })
  .catch(async (err) => {
    console.error("Seed failed:", err);
    await pool.end();
    process.exit(1);
  });
